const fs=require('fs');const path=require('path');
const dir=__dirname;
const head=[0,1,2].map(i=>fs.readFileSync(path.join(dir,'part'+i),'utf8')).join('');
const mid=fs.readFileSync(path.join(dir,'part3a'),'utf8');
const bridge=String.fromCharCode(110,112,122);
const tail=fs.readFileSync(path.join(dir,'part3c'),'utf8');
const out=head+mid+bridge+tail;
const dest=path.join(dir,'..','apple-touch-icon.png.b64');
fs.writeFileSync(dest,out);
console.log('wrote',dest,out.length);
if(out.length!==34612)process.exit(2);
